# .github/workflows/deploy.yml
name: Happy-Card CI/CD Docker Deployment

on:
  push:
    branches:
      - deploy # Works when pushed to deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HAPPY_DOCKER_USERNAME }}
          password: ${{ secrets.HAPPY_DOCKER_TOKEN }}

      # Docker image build & push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./happy.dockerfile
          push: true
          tags: ${{ secrets.HAPPY_DOCKER_USERNAME }}/happy-card:latest

      # Deploy to server via SSH
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HAPPY_PUBLIC_IP }}
          username: cheonbi
          key: ${{ secrets.HAPPY_PRIVATE_KEY }}
          port: 22
          # run deploy shell script
          script: |
            ~/happy_deploy.sh
